---
- name: create /opt/local-path-provisioner
  file: path=/opt/local-path-provisioner state=directory

- name: apply K8s definitions
  delegate_to: self
  command: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

- name: set local-path storage class to be the default
  delegate_to: self
  command: "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"
