#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
# Purpose:
# - build k3s on target host
############################################################################
# Localhost Prep Tasks
- name: MSIO | Kargo | K3s Deploy | ansible/run-k3s
  hosts: kargo
  vars:
    module: "k3s"
    ansible_name_module: "Konductor | CCIO | {{ ansible_os_family }} | {{ module }}"
  vars_files:
    - 'vars/global.yml'
    - 'vars/{{ ansible_os_family }}.yml'
  roles:
    - kargo
