#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: 'CCIO | Kargo'
  hosts: kargo
  vars:
    module: "kargo"
    ansible_name_module: "CCIO | Kargo | {{ ansible_os_family }} | {{ module }}"
  vars_files:
    - vars/global.yml

- import_playbook: packages.yml
- import_playbook: openvswitch.yml
- import_playbook: libvirt.yml
- import_playbook: grub.yml
- import_playbook: resolver.yml
# import_playbook: prep.yml
# import_playbook: k3s.yml
# import_playbook: kargo.yml
