# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: registry-image-datavolume
spec:
  source:
    registry:
      url: "docker://quay.io/codesparta/rhel-kvm"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 28Gi
