apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: host-br10-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "br10-l2",
        "plugins": [{
            "type": "bridge",
            "bridge": "br10",
            "ipam": {}
        }]
    }

### Annotation Example
# annotations:
#   k8s.v1.cni.cncf.io/networks: host-br10-network
