---
#apiVersion: networking.k8s.io/v1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceph-dashboard
spec:
  rules:
  - host: ceph.magic.io
    http:
      paths:
      - backend:
          serviceName: ceph-http
          servicePort: 7000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  name: rook-ceph-mgr-dashboard-external-http
  namespace: rook-ceph
spec:
  clusterIP: 10.43.135.255
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
