---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
spec:
  rules:
  - host: gitea.magic.io
    http:
      paths:
      - backend:
          serviceName: gitea-http
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.12.6
    helm.sh/chart: gitea-2.0.4
  name: gitea-http
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  sessionAffinity: None
  type: ClusterIP
