---
# Install Base Packages on Fedora
- name: Install Base Packages on Fedora OS
  become: yes
  package:
    name: "{{ packages_ovs_fedora }}"
    state: present

- name: Enable & Start OpenVSwitch Service
  become: yes
  service:
    name: openvswitch
    state: started
    enabled: yes
